/*
 * 用户组管理API
 *
 * 这是一个对用户组进行创建、修改、检索、和删除的API
 *
 * API version: 3.11
 * Contact: huanghui@zdns.cn
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"log"
	"net/http"

	//以下包用来转换yaml
	"io/ioutil"

	"github.com/ghodss/yaml"
)

func UserGroupsGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("{\"Handler\": \"UserGroupsGet arrived.\"}"))
}

func UserGroupsIdDelete(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("{\"Handler\": \"UserGroupsIdDelete arrived.\"}"))
}

func UserGroupsPost(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("{\"Handler\": \"UserGroupsPost arrived.\"}"))
}

func SwaggerJson(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.WriteHeader(http.StatusOK)
	buffer, err := ioutil.ReadFile("./api/swagger.yaml")
	var jsonbody []byte
	if err != nil {
		log.Fatalf(err.Error())
	} else {
		jsonbody, err = yaml.YAMLToJSON(buffer)
		if err != nil {
			log.Fatalf(err.Error())
		}
	}
	w.Write(jsonbody)
}
