/*
 * 用户组管理API
 *
 * 这是一个对用户组进行创建、修改、检索、和删除的API
 *
 * API version: 3.11
 * Contact: huanghui@zdns.cn
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {

	Resources []InlineResponse200Resources `json:"resources,omitempty"`

	PageNum int64 `json:"page_num,omitempty"`

	PageSize int64 `json:"page_size,omitempty"`

	TotalSize int64 `json:"total_size,omitempty"`
}
